global:
  scrape_interval: 15s  # Собирать метрики каждые 15 секунд

scrape_configs:
  # Собираем метрики с FastAPI
  - job_name: 'habit-tracker-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']  # Имя сервиса и порт внутри сети Docker

  # Собираем метрики с Celery (Redis)
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']  # Имя сервиса и порт внутри сети Docker
