name: CI Pipeline

# Триггеры для запуска воркфлоу
on:
  push:
    branches: [ "main", "dev" ]  # Запуск на пуши в main и dev
  pull_request:
    branches: [ "main" ]  # Запуск на создание/обновление PR в main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Запускаем на последней версии Ubuntu

    # Определяем "матрицу стратегий", чтобы легко запускать тесты на нескольких версиях Python и убедиться в совместимости
    strategy:
      fail-fast: false  # Не отменять другие задачи, если одна упала
      matrix:
        python-version: ["3.12"]  # Можно добавить другие, например, "3.11"

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "latest"

      # 3. Устанавливаем зависимости проекта с кэшированием
      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true  # Создаем .venv в корне проекта для кэширования

      # 4. Запускаем все проверки качества кода и тесты через Makefile
      #    Тесты будут использовать сервис test-db из docker-compose.yml
      - name: Run quality checks and tests
        run: make check
